try-catch both test failed

diff --git a/JenkinsFilePipeline3.txt b/JenkinsFilePipeline3.txt
--- a/JenkinsFilePipeline3.txt
+++ b/JenkinsFilePipeline3.txt
@@ -10,34 +10,34 @@ pipeline {
             parallel {
                 stage('Test PROD') {
                     steps {
-                          // script {
-                          //     try {
-                          //         echo 'Test Stage PRD'
-                          //        sh 'exit 1'
-                          //     } catch (e) {
-                          //         echo "Failure in test PROD ${e}"
-                          // }
-                          // }
-                          catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-                             echo 'Test Stage PRD'
-                             sh 'exit 1'
+                          script {
+                              try {
+                                  echo 'Test Stage PRD'
+                                 sh 'exit 1'
+                              } catch (e) {
+                                  echo "Failure in test PROD ${e}"
                           }
+                          }
+                        //   catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                        //      echo 'Test Stage PRD'
+                        //      sh 'exit 1'
+                        //   }
                     }
                 }
                 stage('Test NON PROD') {
                     steps {
-                         // script {
-                         //     try {
-                         //         echo 'Test Stage NON PROD'
-                         //        // exit 1
-                         //     } catch (e) {
-                         //         echo "Failure in test NON PROD ${e}"
-                         //     }
-                         // }
-                         catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-                            echo 'Test Stage PRD'
-                            sh 'exit 1'
+                         script {
+                             try {
+                                 echo 'Test Stage NON PROD'
+                                sh 'exit 1'
+                             } catch (e) {
+                                 echo "Failure in test NON PROD ${e}"
+                             }
                          }
+                        //  catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                        //     echo 'Test Stage PRD'
+                        //     sh 'exit 1'
+                        //  }
                     }
                 }
             }
